
spring:
    application:
        name: rabbitmq-hello
    rabbitmq:
        host: 127.0.0.1
        listener:
            direct:
                retry:
                    max-attempts: 3
        password: guest
        port: 5672
        publisher-confirms: false
        username: guest
server:
  port: 8088
